-- =============================================================================
-- V1__baseline.sql — service-player
--
-- Generated with pg_dump from the schema that Hibernate's ddl-auto: update had
-- built, then cleaned by hand. From this migration onward Flyway owns the
-- schema and Hibernate only validates it (spring.jpa.hibernate.ddl-auto).
--
-- ONCE APPLIED, THIS FILE IS IMMUTABLE. Flyway stores a checksum of its
-- contents and refuses to start when they no longer match. Change the schema
-- by adding V2, V3, ... — never by editing this file.
--
-- Two departures from the raw dump, both deliberate:
--
--   1. players.level and players.experience_points are dropped. Those columns
--      are accretion: the stats moved to GameCharacter in b6a8dd9 and
--      ddl-auto: update never removes anything. No entity maps them, and
--      Hibernate's validate does not report extra columns, so they would have
--      stayed invisible forever. They are NOT NULL with no default, which
--      means an insert of a new player against that schema fails.
--
--   2. Table and column names are unqualified, which keeps the migration
--      schema agnostic. Each service now owns a schema of its own (B2) and
--      Flyway targets it via spring.flyway.schemas; a hardcoded `public.`
--      prefix here would have pinned these tables to the wrong schema.
-- =============================================================================

CREATE TABLE players (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id       uuid NOT NULL DEFAULT gen_random_uuid(),
    zitadel_user_id varchar(255) NOT NULL,
    display_name    varchar(255) NOT NULL,
    profile_icon    varchar(255) NOT NULL DEFAULT 'pi-user',
    created_at      timestamp(6) with time zone NOT NULL,
    updated_at      timestamp(6) with time zone NOT NULL,

    CONSTRAINT players_pkey PRIMARY KEY (id),
    CONSTRAINT uq_players_public_id UNIQUE (public_id),
    CONSTRAINT uq_players_zitadel_user_id UNIQUE (zitadel_user_id),
    CONSTRAINT uq_players_display_name UNIQUE (display_name)
);

CREATE TABLE characters (
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id         uuid NOT NULL,
    player_id         bigint NOT NULL,
    name              varchar(255) NOT NULL,
    level             integer NOT NULL,
    experience_points bigint NOT NULL,
    created_at        timestamp(6) with time zone NOT NULL,
    updated_at        timestamp(6) with time zone NOT NULL,

    CONSTRAINT characters_pkey PRIMARY KEY (id),
    CONSTRAINT uq_characters_public_id UNIQUE (public_id),
    CONSTRAINT fk_characters_player FOREIGN KEY (player_id) REFERENCES players (id)
);
