-- =============================================================================
-- V4__outbox.sql — service-player
--
-- The transactional outbox. The insert happens in the transaction that creates
-- the player, so the fact and the intent to publish it commit together or not
-- at all. A separate scheduled step publishes the row to RabbitMQ.
--
-- public_id is the eventId consumers deduplicate on. payload holds the data
-- object alone, because the envelope fields are columns here. published_at
-- NULL means pending, and the publisher deletes a published row after 30 days:
-- the lasting record of a fact is the audit events collection, not this table.
-- =============================================================================

CREATE TABLE outbox (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id     uuid NOT NULL DEFAULT gen_random_uuid(),
    event_type    varchar(100) NOT NULL,
    event_version integer NOT NULL,
    aggregate_id  uuid NOT NULL,
    payload       jsonb NOT NULL,
    published_at  timestamp(6) with time zone,
    created_at    timestamp(6) with time zone NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    created_by    uuid,
    updated_by    uuid,

    CONSTRAINT outbox_pkey PRIMARY KEY (id),
    CONSTRAINT uq_outbox_public_id UNIQUE (public_id)
);

-- Serves: SELECT ... WHERE published_at IS NULL ORDER BY id FOR UPDATE SKIP LOCKED
CREATE INDEX idx_outbox_pending ON outbox (id) WHERE published_at IS NULL;
