-- =============================================================================
-- V2__purchase_identity_and_audit.sql — service-commerce
--
-- Brings purchases onto BaseEntity (ADR 0013) and changes what player_id
-- means (ADR 0014).
--
-- Three changes:
--
--   1. The primary key was the public UUID. That UUID becomes public_id and a
--      generated bigint becomes the key, so this table is shaped like every
--      other one. The API keeps exchanging the same UUID.
--
--   2. player_id held a Zitadel subject, typed varchar. It now holds the
--      player's publicId, typed uuid. There is no foreign key: commerce has
--      no rights in the player schema, so this is a reference it cannot
--      validate.
--
--   3. purchased_at is renamed to created_at — it always recorded the same
--      instant — and the three remaining audit columns are added.
--
-- THIS MIGRATION DELETES EVERY ROW. 'player-001' is not a UUID, so no cast
-- turns the existing values into one, and inventing UUIDs for them would
-- fabricate a ledger. The only rows that have ever existed are the five in
-- data.sql, reinserted on the next start, and nothing is deployed. If that
-- ever stops being true, this file is wrong.
-- =============================================================================

DELETE FROM purchases;

-- 1. the key
ALTER TABLE purchases DROP CONSTRAINT purchases_pkey;
ALTER TABLE purchases RENAME COLUMN id TO public_id;
ALTER TABLE purchases ALTER COLUMN public_id SET DEFAULT gen_random_uuid();
ALTER TABLE purchases ADD CONSTRAINT uq_purchases_public_id UNIQUE (public_id);

ALTER TABLE purchases ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE purchases ADD CONSTRAINT purchases_pkey PRIMARY KEY (id);

-- 2. the player reference
ALTER TABLE purchases ALTER COLUMN player_id TYPE uuid USING player_id::uuid;

-- 3. the audit columns
ALTER TABLE purchases RENAME COLUMN purchased_at TO created_at;
ALTER TABLE purchases ADD COLUMN updated_at timestamp(6) with time zone NOT NULL;
ALTER TABLE purchases ADD COLUMN created_by uuid;
ALTER TABLE purchases ADD COLUMN updated_by uuid;
