#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# zitadel-setup.sh — Create this platform's Zitadel objects from code.
#
# Replaces the clicking: the project, its three roles, the portal's OIDC
# client, and the provisioning target and execution behind ADR 0018.
#
# Idempotent. Every step looks for the object first and only creates what is
# missing, so running it twice changes nothing.
#
# Two values are generated by Zitadel rather than chosen here — the OIDC client
# id and the target's signing key — so the script writes them back into .env,
# .client-id and the portal's environment.ts. That write-back is the whole
# reason this is a script rather than a document.
#
# Usage:
#   cd infrastructure && docker compose up -d && ./zitadel-setup.sh
#
# Requires: docker compose, curl, jq. The admin PAT comes from the service
# account Zitadel creates at instance init (see ZITADEL_FIRSTINSTANCE_* in
# docker-compose.yml); set ZITADEL_ADMIN_PAT to override it.
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
CLIENT_ID_FILE="${SCRIPT_DIR}/.client-id"
FRONTEND_ENV="${SCRIPT_DIR}/../frontend-portal/src/environments/environment.ts"
PAT_FILENAME="admin.pat"
# Any tiny image with a shell; only used to read one file out of a volume.
PAT_READER_IMAGE="alpine"

# key:displayName — the keys are the contract with @PreAuthorize and the
# frontend's PlatformRole enum; the display names are what the console shows.
ROLE_KEYS=(player:Player game_master:"Game Master" platform_admin:"Platform Admin")

# ── Output helpers ─────────────────────────────────────────────────────────
# Values are never printed. Ids are, names are; tokens and keys are not.
info() { echo "   $*"; }
step() { echo "▶  $*"; }
done_() { echo "✅ $*"; }
fail() {
  echo "❌ $*" >&2
  exit 1
}

# ── Preflight ──────────────────────────────────────────────────────────────
require_tools() {
  local tool
  for tool in docker curl jq; do
    command -v "${tool}" >/dev/null 2>&1 || fail "${tool} is required but not installed."
  done
}

load_env() {
  [[ -f "${ENV_FILE}" ]] || fail "No .env at ${ENV_FILE}. Copy .env.example first."

  # Safe key=value parser — never executes .env as shell (SC1090).
  local key value
  while IFS='=' read -r key value; do
    [[ -z "${key}" || "${key}" == \#* ]] && continue
    export "${key}=${value}"
  done <"${ENV_FILE}"
}

require_env() {
  local name
  for name in "$@"; do
    [[ -n "${!name:-}" ]] || fail "${name} is not set in ${ENV_FILE}"
  done
}

# ── Authentication ─────────────────────────────────────────────────────────
# The PAT lives in the bootstrap volume, written by Zitadel at instance init.
# It is read into a variable and never echoed.
read_admin_pat() {
  if [[ -n "${ZITADEL_ADMIN_PAT:-}" ]]; then
    info "Using ZITADEL_ADMIN_PAT from the environment"
    PAT_IS_OURS=false
    return
  fi
  PAT_IS_OURS=true

  # The Zitadel image is distroless, so it has no shell and no cat to exec.
  # Read the file by mounting the same volume into a container that does.
  local container volume
  container="$(docker compose --project-directory "${SCRIPT_DIR}" ps -q zitadel-api)"
  [[ -n "${container}" ]] || fail "zitadel-api is not running. Start the stack first."

  volume="$(docker inspect "${container}" \
    --format '{{range .Mounts}}{{if eq .Destination "/zitadel/bootstrap"}}{{.Name}}{{end}}{{end}}')"
  [[ -n "${volume}" ]] || fail "zitadel-api has no volume mounted at /zitadel/bootstrap."

  ZITADEL_ADMIN_PAT="$(docker run --rm -v "${volume}:/bootstrap:ro" "${PAT_READER_IMAGE}" \
    cat "/bootstrap/${PAT_FILENAME}" 2>/dev/null | tr -d '[:space:]')" || true

  [[ -n "${ZITADEL_ADMIN_PAT}" ]] || fail \
    "No ${PAT_FILENAME} in the zitadel-api bootstrap volume.
   Zitadel writes it only when an instance is first initialised, so an instance
   created before ZITADEL_FIRSTINSTANCE_ORG_MACHINE_* was added to
   docker-compose.yml does not have one.

   Do not recreate the instance for this. In the console: Users → Service Users
   → New, then give that user IAM_OWNER under Instance → Administrators, then
   open it and create a Personal Access Token. Put the token in .env as
   ZITADEL_ADMIN_PAT and run this again. A fresh environment needs none of
   that — the service account is created for it automatically."

  export ZITADEL_ADMIN_PAT
}

# Confirms the token still works and returns the account it belongs to. A
# revoked token fails here rather than halfway through creating things.
identify_caller() {
  local response status
  response="$(curl -sS -w $'\n%{http_code}' "${ZITADEL_ISSUER_URI%/}/auth/v1/users/me" \
    -H "Authorization: Bearer ${ZITADEL_ADMIN_PAT}")"
  status="${response##*$'\n'}"

  if [[ "${status}" == "401" || "${status}" == "403" ]]; then
    fail "The admin token is not valid any more (HTTP ${status}).

   If setup has already run once, this is expected: it revokes its own token on
   success, so the copy left in the bootstrap volume is dead. Zitadel is already
   configured and there is normally nothing to do.

   To run setup again, supply a working token as ZITADEL_ADMIN_PAT, or rebuild
   the instance from scratch — which this script exists to make cheap."
  fi

  ADMIN_USER_ID="$(jq -r '.user.id' <<<"${response%$'\n'*}")"
  [[ -n "${ADMIN_USER_ID}" && "${ADMIN_USER_ID}" != "null" ]] ||
    fail "Could not read the admin account id from /auth/v1/users/me."
}

# ── Dropping privilege ─────────────────────────────────────────────────────
# Everything above needs IAM_OWNER, because Actions targets are instance-level
# resources — ORG_OWNER reaches projects, roles and clients but not those. Once
# the objects exist, nothing needs that power again, so the token goes.
#
# The expiry date in .env is only a backstop for a run that dies before this.
revoke_admin_pat() {
  if [[ "${PAT_IS_OURS}" != true ]]; then
    info "Token came from ZITADEL_ADMIN_PAT, leaving it alone"
    return
  fi
  if [[ "${ZITADEL_SETUP_REVOKE_ADMIN:-true}" != true ]]; then
    info "ZITADEL_SETUP_REVOKE_ADMIN is not true, keeping the token"
    return
  fi

  step "Revoking the setup token"

  local token_id
  token_id="$(api POST "/management/v1/users/${ADMIN_USER_ID}/pats/_search" '{}' |
    jq -r '.result[0].id // empty')"

  if [[ -z "${token_id}" ]]; then
    info "no token found to revoke"
    return
  fi

  api DELETE "/management/v1/users/${ADMIN_USER_ID}/pats/${token_id}" >/dev/null
  done_ "IAM_OWNER token revoked — the account survives, its token does not"
}

# ── API plumbing ───────────────────────────────────────────────────────────
# Prints the response body on success; on any non-2xx prints the body and the
# status to stderr and stops, because a half-configured instance is worse than
# an unconfigured one.
api() {
  local method="$1" path="$2" body="${3:-}"
  local url="${ZITADEL_ISSUER_URI%/}${path}"
  local response status payload

  if [[ -n "${body}" ]]; then
    response="$(curl -sS -w $'\n%{http_code}' -X "${method}" "${url}" \
      -H "Authorization: Bearer ${ZITADEL_ADMIN_PAT}" \
      -H "Content-Type: application/json" \
      -d "${body}")"
  else
    response="$(curl -sS -w $'\n%{http_code}' -X "${method}" "${url}" \
      -H "Authorization: Bearer ${ZITADEL_ADMIN_PAT}")"
  fi

  status="${response##*$'\n'}"
  payload="${response%$'\n'*}"

  if [[ "${status}" != 2* ]]; then
    echo "   ${method} ${path} → ${status}" >&2
    echo "   ${payload}" >&2
    fail "Zitadel rejected the call above."
  fi

  echo "${payload}"
}

# ── .env write-back ────────────────────────────────────────────────────────
set_env_value() {
  local key="$1" value="$2"

  if grep -q "^${key}=" "${ENV_FILE}"; then
    # The value can contain slashes, so use a delimiter that cannot appear.
    sed -i "s|^${key}=.*|${key}=${value}|" "${ENV_FILE}"
  else
    printf '%s=%s\n' "${key}" "${value}" >>"${ENV_FILE}"
  fi
}

# ── Steps ──────────────────────────────────────────────────────────────────
find_or_create_project() {
  step "Project: ${ZITADEL_PROJECT_NAME}"

  local existing
  existing="$(api POST /management/v1/projects/_search \
    "$(jq -nc --arg name "${ZITADEL_PROJECT_NAME}" \
      '{queries:[{nameQuery:{name:$name,method:"TEXT_QUERY_METHOD_EQUALS"}}]}')" |
    jq -r '.result[0].id // empty')"

  if [[ -n "${existing}" ]]; then
    PROJECT_ID="${existing}"
    info "already exists (${PROJECT_ID})"
    return
  fi

  # projectRoleAssertion is what puts the roles claim in the token, and
  # projectRoleCheck refuses a login by a user with no role on the project.
  # Without the first, ZitadelRoleConverter would find nothing to convert.
  PROJECT_ID="$(api POST /management/v1/projects \
    "$(jq -nc --arg name "${ZITADEL_PROJECT_NAME}" \
      '{name:$name, projectRoleAssertion:true, projectRoleCheck:true}')" | jq -r '.id')"
  done_ "created project ${PROJECT_ID}"
}

ensure_roles() {
  step "Project roles"

  local existing entry key display
  existing="$(api POST "/management/v1/projects/${PROJECT_ID}/roles/_search" '{}' |
    jq -r '.result[]?.key')"

  for entry in "${ROLE_KEYS[@]}"; do
    key="${entry%%:*}"
    display="${entry#*:}"

    if grep -qx "${key}" <<<"${existing}"; then
      info "${key} already exists"
      continue
    fi
    api POST "/management/v1/projects/${PROJECT_ID}/roles" \
      "$(jq -nc --arg key "${key}" --arg display "${display}" \
        '{roleKey:$key, displayName:$display}')" >/dev/null
    done_ "created role ${key}"
  done
}

find_or_create_oidc_app() {
  step "OIDC client: ${ZITADEL_OIDC_APP_NAME}"

  local existing
  existing="$(api POST "/management/v1/projects/${PROJECT_ID}/apps/_search" '{}' |
    jq -r --arg name "${ZITADEL_OIDC_APP_NAME}" \
      '.result[]? | select(.name == $name) | .oidcConfig.clientId // empty')"

  if [[ -n "${existing}" ]]; then
    PORTAL_CLIENT_ID="${existing}"
    info "already exists (${PORTAL_CLIENT_ID})"
    return
  fi

  # Public client, authorization code + PKCE, no secret: the portal is a SPA
  # and the Unity client will be native (F1). Neither can hold a secret.
  PORTAL_CLIENT_ID="$(api POST "/management/v1/projects/${PROJECT_ID}/apps/oidc" \
    "$(jq -nc \
      --arg name "${ZITADEL_OIDC_APP_NAME}" \
      --arg redirect "${ZITADEL_OIDC_REDIRECT_URI}" \
      --arg logout "${ZITADEL_OIDC_POST_LOGOUT_URI}" \
      --arg origin "${ZITADEL_OIDC_ALLOWED_ORIGIN}" \
      '{
         name: $name,
         redirectUris: [$redirect],
         postLogoutRedirectUris: [$logout],
         responseTypes: ["OIDC_RESPONSE_TYPE_CODE"],
         grantTypes: ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
         appType: "OIDC_APP_TYPE_USER_AGENT",
         authMethodType: "OIDC_AUTH_METHOD_TYPE_NONE",
         accessTokenType: "OIDC_TOKEN_TYPE_JWT",
         accessTokenRoleAssertion: true,
         idTokenRoleAssertion: true,
         idTokenUserinfoAssertion: true,
         additionalOrigins: [$origin]
       }')" | jq -r '.clientId')"
  done_ "created OIDC client ${PORTAL_CLIENT_ID}"
}

ensure_target() {
  step "Provisioning target"

  # Results come back under .targets, and each one carries its signingKey — so
  # an existing target needs no special handling, the key is simply read back.
  local existing
  existing="$(api POST /v2/actions/targets/search '{}' |
    jq -c --arg name "${TARGET_NAME}" \
      '.targets[]? | select(.name == $name) | {id, signingKey}')"

  if [[ -n "${existing}" ]]; then
    TARGET_ID="$(jq -r '.id' <<<"${existing}")"
    SIGNING_KEY="$(jq -r '.signingKey' <<<"${existing}")"
    info "already exists (${TARGET_ID})"
    return
  fi

  local created
  created="$(api POST /v2/actions/targets \
    "$(jq -nc \
      --arg name "${TARGET_NAME}" \
      --arg endpoint "${ZITADEL_TARGET_ENDPOINT}" \
      '{
         name: $name,
         endpoint: $endpoint,
         timeout: "10s",
         restWebhook: {interruptOnError: false}
       }')")"

  TARGET_ID="$(jq -r '.id' <<<"${created}")"
  SIGNING_KEY="$(jq -r '.signingKey' <<<"${created}")"
  done_ "created target ${TARGET_ID}"
}

ensure_execution() {
  step "Execution on ${PROVISIONING_EVENT}"

  api PUT /v2/actions/executions \
    "$(jq -nc --arg event "${PROVISIONING_EVENT}" --arg target "${TARGET_ID}" \
      '{condition: {event: {event: $event}}, targets: [$target]}')" >/dev/null
  done_ "execution points at ${TARGET_ID}"
}

write_back() {
  step "Writing generated values back"

  set_env_value ZITADEL_PORTAL_CLIENT_ID "${PORTAL_CLIENT_ID}"
  printf '%s\n' "${PORTAL_CLIENT_ID}" >"${CLIENT_ID_FILE}"
  info "client id → .env, .client-id"

  if [[ -n "${SIGNING_KEY:-}" ]]; then
    set_env_value ZITADEL_WEBHOOK_SIGNING_KEY "${SIGNING_KEY}"
    info "signing key → .env"
  fi

  # The portal bakes the client id in at build time, so it lives in a source
  # file. A change here belongs in a commit, which is why it is patched rather
  # than written to some untracked place.
  if [[ -f "${FRONTEND_ENV}" ]]; then
    sed -i "s|zitadelClientId: '[^']*'|zitadelClientId: '${PORTAL_CLIENT_ID}'|" "${FRONTEND_ENV}"
    info "client id → environment.ts (check git diff)"
  fi
}

main() {
  require_tools
  load_env
  require_env ZITADEL_ISSUER_URI ZITADEL_PROJECT_NAME ZITADEL_OIDC_APP_NAME \
    ZITADEL_OIDC_REDIRECT_URI ZITADEL_OIDC_POST_LOGOUT_URI \
    ZITADEL_OIDC_ALLOWED_ORIGIN ZITADEL_TARGET_ENDPOINT

  TARGET_NAME="player-provisioning"
  PROVISIONING_EVENT="user.human.added"

  read_admin_pat
  identify_caller

  find_or_create_project
  ensure_roles
  find_or_create_oidc_app
  ensure_target
  ensure_execution
  write_back
  revoke_admin_pat

  echo
  done_ "Zitadel is configured. Restart service-player so it picks up the signing key."
}

main "$@"
