#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# zitadel-setup.sh — Create this platform's Zitadel objects from code.
#
# Replaces the clicking: the project, its three roles, the portal's OIDC
# client, and the provisioning target and execution behind ADR 0018.
#
# Idempotent. Every step looks for the object first and only creates what is
# missing, so running it twice changes nothing.
#
# Two values are generated by Zitadel rather than chosen here — the OIDC client
# id and the target's signing key — so the script writes them back into .env,
# .client-id and the portal's config.json. That write-back is the whole reason
# this is a script rather than a document.
#
# Usage:
#   cd infrastructure && docker compose up -d && ./zitadel-setup.sh
#
# Requires: docker compose, curl, jq. The admin PAT comes from the service
# account Zitadel creates at instance init (see ZITADEL_FIRSTINSTANCE_* in
# docker-compose.yml); set ZITADEL_ADMIN_PAT to override it.
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
CLIENT_ID_FILE="${SCRIPT_DIR}/.client-id"
PORTAL_CONFIG="${SCRIPT_DIR}/../frontend-portal/public/config.json"
PAT_FILENAME="admin.pat"
# Any tiny image with a shell; only used to read one file out of a volume.
PAT_READER_IMAGE="alpine"

# key:displayName — the keys are the contract with @PreAuthorize and the
# frontend's PlatformRole enum; the display names are what the console shows.
ROLE_KEYS=(player:Player game_master:"Game Master" platform_admin:"Platform Admin")

# ── Output helpers ─────────────────────────────────────────────────────────
# Values are never printed. Ids are, names are; tokens and keys are not.
info() { echo "   $*"; }
step() { echo "▶  $*"; }
done_() { echo "✅ $*"; }
fail() {
  echo "❌ $*" >&2
  exit 1
}

# ── Preflight ──────────────────────────────────────────────────────────────
require_tools() {
  local tool
  for tool in docker curl jq; do
    command -v "${tool}" >/dev/null 2>&1 || fail "${tool} is required but not installed."
  done
}

load_env() {
  [[ -f "${ENV_FILE}" ]] || fail "No .env at ${ENV_FILE}. Copy .env.example first."

  # Safe key=value parser — never executes .env as shell (SC1090).
  local key value
  while IFS='=' read -r key value; do
    [[ -z "${key}" || "${key}" == \#* ]] && continue
    export "${key}=${value}"
  done <"${ENV_FILE}"
}

require_env() {
  local name
  for name in "$@"; do
    [[ -n "${!name:-}" ]] || fail "${name} is not set in ${ENV_FILE}"
  done
}

# ── Authentication ─────────────────────────────────────────────────────────
# The PAT lives in the bootstrap volume, written by Zitadel at instance init.
# It is read into a variable and never echoed.
read_admin_pat() {
  if [[ -n "${ZITADEL_ADMIN_PAT:-}" ]]; then
    info "Using ZITADEL_ADMIN_PAT from the environment"
    PAT_IS_OURS=false
    return
  fi
  PAT_IS_OURS=true

  # The Zitadel image is distroless, so it has no shell and no cat to exec.
  # Read the file by mounting the same volume into a container that does.
  local container volume
  container="$(docker compose --project-directory "${SCRIPT_DIR}" ps -q zitadel-api)"
  [[ -n "${container}" ]] || fail "zitadel-api is not running. Start the stack first."

  volume="$(docker inspect "${container}" \
    --format '{{range .Mounts}}{{if eq .Destination "/zitadel/bootstrap"}}{{.Name}}{{end}}{{end}}')"
  [[ -n "${volume}" ]] || fail "zitadel-api has no volume mounted at /zitadel/bootstrap."

  ZITADEL_ADMIN_PAT="$(docker run --rm -v "${volume}:/bootstrap:ro" "${PAT_READER_IMAGE}" \
    cat "/bootstrap/${PAT_FILENAME}" 2>/dev/null | tr -d '[:space:]')" || true

  [[ -n "${ZITADEL_ADMIN_PAT}" ]] || fail \
    "No ${PAT_FILENAME} in the zitadel-api bootstrap volume.
   Zitadel writes it only when an instance is first initialised, so an instance
   created before ZITADEL_FIRSTINSTANCE_ORG_MACHINE_* was added to
   docker-compose.yml does not have one.

   Do not recreate the instance for this. In the console: Users → Service Users
   → New, then give that user IAM_OWNER under Instance → Administrators, then
   open it and create a Personal Access Token. Put the token in .env as
   ZITADEL_ADMIN_PAT and run this again. A fresh environment needs none of
   that — the service account is created for it automatically."

  export ZITADEL_ADMIN_PAT
}

# Confirms the token still works and returns the account it belongs to. A
# revoked token fails here rather than halfway through creating things.
identify_caller() {
  local response status
  response="$(curl -sS -w $'\n%{http_code}' "${ZITADEL_ISSUER_URI%/}/auth/v1/users/me" \
    -H "Authorization: Bearer ${ZITADEL_ADMIN_PAT}")"
  status="${response##*$'\n'}"

  if [[ "${status}" == "401" || "${status}" == "403" ]]; then
    fail "The admin token is not valid any more (HTTP ${status}).

   If setup has already run once, this is expected: it revokes its own token on
   success, so the copy left in the bootstrap volume is dead. Zitadel is already
   configured and there is normally nothing to do.

   To run setup again, supply a working token as ZITADEL_ADMIN_PAT, or rebuild
   the instance from scratch — which this script exists to make cheap."
  fi

  ADMIN_USER_ID="$(jq -r '.user.id' <<<"${response%$'\n'*}")"
  [[ -n "${ADMIN_USER_ID}" && "${ADMIN_USER_ID}" != "null" ]] ||
    fail "Could not read the admin account id from /auth/v1/users/me."
}

# ── Dropping privilege ─────────────────────────────────────────────────────
# Everything above needs IAM_OWNER, because Actions targets are instance-level
# resources — ORG_OWNER reaches projects, roles and clients but not those. Once
# the objects exist, nothing needs that power again, so the token goes.
#
# The expiry date in .env is only a backstop for a run that dies before this.
revoke_admin_pat() {
  if [[ "${PAT_IS_OURS}" != true ]]; then
    info "Token came from ZITADEL_ADMIN_PAT, leaving it alone"
    return
  fi
  if [[ "${ZITADEL_SETUP_REVOKE_ADMIN:-true}" != true ]]; then
    info "ZITADEL_SETUP_REVOKE_ADMIN is not true, keeping the token"
    return
  fi

  step "Revoking the setup token"

  local token_id
  token_id="$(api POST "/management/v1/users/${ADMIN_USER_ID}/pats/_search" '{}' |
    jq -r '.result[0].id // empty')"

  if [[ -z "${token_id}" ]]; then
    info "no token found to revoke"
    return
  fi

  api DELETE "/management/v1/users/${ADMIN_USER_ID}/pats/${token_id}" >/dev/null
  done_ "IAM_OWNER token revoked — the account survives, its token does not"
}

# ── API plumbing ───────────────────────────────────────────────────────────
# Prints the response body on success; on any non-2xx prints the body and the
# status to stderr and stops, because a half-configured instance is worse than
# an unconfigured one.
api() {
  local method="$1" path="$2" body="${3:-}"
  local url="${ZITADEL_ISSUER_URI%/}${path}"
  local response status payload

  if [[ -n "${body}" ]]; then
    response="$(curl -sS -w $'\n%{http_code}' -X "${method}" "${url}" \
      -H "Authorization: Bearer ${ZITADEL_ADMIN_PAT}" \
      -H "Content-Type: application/json" \
      -d "${body}")"
  else
    response="$(curl -sS -w $'\n%{http_code}' -X "${method}" "${url}" \
      -H "Authorization: Bearer ${ZITADEL_ADMIN_PAT}")"
  fi

  status="${response##*$'\n'}"
  payload="${response%$'\n'*}"

  if [[ "${status}" != 2* ]]; then
    echo "   ${method} ${path} → ${status}" >&2
    echo "   ${payload}" >&2
    fail "Zitadel rejected the call above."
  fi

  echo "${payload}"
}

# ── .env write-back ────────────────────────────────────────────────────────
# What gets written here is generated by Zitadel — an id, a token, a signing
# key — so it must not pass through a sed replacement, where & means "the whole
# match" and a backslash escapes. A secret corrupted that way would be written
# without complaint and fail somewhere else entirely. awk reads the value from
# the environment instead and writes it exactly as given.
#
# The new text goes to a temp file and only overwrites .env once awk has
# succeeded, so an edit that dies halfway cannot truncate it. The temp file is
# copied through the original rather than moved onto it, so the mode and owner
# survive — .env holds secrets and its permissions are not ours to change.
set_env_value() {
  local key="$1" value="$2" tmp status

  if ! grep -q "^${key}=" "${ENV_FILE}"; then
    printf '%s=%s\n' "${key}" "${value}" >>"${ENV_FILE}"
    return
  fi

  tmp="$(mktemp)" || return 1

  if env_key="${key}" env_value="${value}" awk '
      BEGIN { prefix = ENVIRON["env_key"] "=" }
      index($0, prefix) == 1 { print prefix ENVIRON["env_value"]; next }
      { print }
    ' "${ENV_FILE}" >"${tmp}" && cat "${tmp}" >"${ENV_FILE}"; then
    status=0
  else
    status=1
  fi

  rm -f "${tmp}"
  return "${status}"
}

# ── Steps ──────────────────────────────────────────────────────────────────
find_or_create_project() {
  step "Project: ${ZITADEL_PROJECT_NAME}"

  local existing
  existing="$(api POST /management/v1/projects/_search \
    "$(jq -nc --arg name "${ZITADEL_PROJECT_NAME}" \
      '{queries:[{nameQuery:{name:$name,method:"TEXT_QUERY_METHOD_EQUALS"}}]}')" |
    jq -r '.result[0].id // empty')"

  if [[ -n "${existing}" ]]; then
    PROJECT_ID="${existing}"
    info "already exists (${PROJECT_ID})"
    return
  fi

  # projectRoleAssertion is what puts the roles claim in the token, and
  # projectRoleCheck refuses a login by a user with no role on the project.
  # Without the first, ZitadelRoleConverter would find nothing to convert.
  PROJECT_ID="$(api POST /management/v1/projects \
    "$(jq -nc --arg name "${ZITADEL_PROJECT_NAME}" \
      '{name:$name, projectRoleAssertion:true, projectRoleCheck:true}')" | jq -r '.id')"
  done_ "created project ${PROJECT_ID}"
}

ensure_roles() {
  step "Project roles"

  local existing entry key display
  existing="$(api POST "/management/v1/projects/${PROJECT_ID}/roles/_search" '{}' |
    jq -r '.result[]?.key')"

  for entry in "${ROLE_KEYS[@]}"; do
    key="${entry%%:*}"
    display="${entry#*:}"

    if grep -qx "${key}" <<<"${existing}"; then
      info "${key} already exists"
      continue
    fi
    api POST "/management/v1/projects/${PROJECT_ID}/roles" \
      "$(jq -nc --arg key "${key}" --arg display "${display}" \
        '{roleKey:$key, displayName:$display}')" >/dev/null
    done_ "created role ${key}"
  done
}

find_or_create_oidc_app() {
  step "OIDC client: ${ZITADEL_OIDC_APP_NAME}"

  local existing
  existing="$(api POST "/management/v1/projects/${PROJECT_ID}/apps/_search" '{}' |
    jq -r --arg name "${ZITADEL_OIDC_APP_NAME}" \
      '.result[]? | select(.name == $name) | .oidcConfig.clientId // empty')"

  if [[ -n "${existing}" ]]; then
    PORTAL_CLIENT_ID="${existing}"
    info "already exists (${PORTAL_CLIENT_ID})"
    return
  fi

  # Public client, authorization code + PKCE, no secret: the portal is a SPA
  # and the Unity client will be native (F1). Neither can hold a secret.
  #
  # devMode is what lets the redirect URI be http. Zitadel refuses http for a
  # USER_AGENT app without it, and every URI here is http://localhost. It must
  # be false wherever the portal is served over https.
  PORTAL_CLIENT_ID="$(api POST "/management/v1/projects/${PROJECT_ID}/apps/oidc" \
    "$(jq -nc \
      --arg name "${ZITADEL_OIDC_APP_NAME}" \
      --arg redirect "${ZITADEL_OIDC_REDIRECT_URI}" \
      --arg logout "${ZITADEL_OIDC_POST_LOGOUT_URI}" \
      --arg origin "${ZITADEL_OIDC_ALLOWED_ORIGIN}" \
      --argjson devmode "${ZITADEL_OIDC_DEV_MODE:-true}" \
      '{
         name: $name,
         redirectUris: [$redirect],
         postLogoutRedirectUris: [$logout],
         responseTypes: ["OIDC_RESPONSE_TYPE_CODE"],
         grantTypes: ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
         appType: "OIDC_APP_TYPE_USER_AGENT",
         authMethodType: "OIDC_AUTH_METHOD_TYPE_NONE",
         devMode: $devmode,
         accessTokenType: "OIDC_TOKEN_TYPE_JWT",
         accessTokenRoleAssertion: true,
         idTokenRoleAssertion: true,
         idTokenUserinfoAssertion: true,
         additionalOrigins: [$origin]
       }')" | jq -r '.clientId')"
  done_ "created OIDC client ${PORTAL_CLIENT_ID}"
}

ensure_target() {
  step "Provisioning target"

  # Results come back under .targets, and each one carries its signingKey — so
  # an existing target needs no special handling, the key is simply read back.
  local existing
  existing="$(api POST /v2/actions/targets/search '{}' |
    jq -c --arg name "${TARGET_NAME}" \
      '.targets[]? | select(.name == $name) | {id, signingKey}')"

  if [[ -n "${existing}" ]]; then
    TARGET_ID="$(jq -r '.id' <<<"${existing}")"
    SIGNING_KEY="$(jq -r '.signingKey' <<<"${existing}")"
    info "already exists (${TARGET_ID})"
    return
  fi

  local created
  created="$(api POST /v2/actions/targets \
    "$(jq -nc \
      --arg name "${TARGET_NAME}" \
      --arg endpoint "${ZITADEL_TARGET_ENDPOINT}" \
      '{
         name: $name,
         endpoint: $endpoint,
         timeout: "10s",
         restWebhook: {interruptOnError: false}
       }')")"

  TARGET_ID="$(jq -r '.id' <<<"${created}")"
  SIGNING_KEY="$(jq -r '.signingKey' <<<"${created}")"
  done_ "created target ${TARGET_ID}"
}

ensure_execution() {
  step "Execution on ${PROVISIONING_EVENT}"

  api PUT /v2/actions/executions \
    "$(jq -nc --arg event "${PROVISIONING_EVENT}" --arg target "${TARGET_ID}" \
      '{condition: {event: {event: $event}}, targets: [$target]}')" >/dev/null
  done_ "execution points at ${TARGET_ID}"
}

# The project is created with projectRoleCheck, so Zitadel refuses to issue a
# token for the portal to a user holding no role on it. That is the gate keeping
# the identity provider's own admin out of the game: administering Zitadel and
# administering the platform are different jobs, and the console at :8080 is
# where the first one happens.
#
# So this grants nobody unless a username is named. An empty value is a
# decision, not an oversight.
grant_bootstrap_admin() {
  step "Bootstrap admin grant"

  if [[ -z "${ZITADEL_BOOTSTRAP_ADMIN_USERNAME:-}" ]]; then
    info "ZITADEL_BOOTSTRAP_ADMIN_USERNAME is empty, granting nobody"
    info "create a portal user in the console and grant it a role there, or name"
    info "it here — until something holds a role, nobody can log in to the portal"
    return
  fi

  local user_id existing
  user_id="$(api POST /management/v1/users/_search '{}' |
    jq -r --arg name "${ZITADEL_BOOTSTRAP_ADMIN_USERNAME}" \
      '[.result[]? | select(.userName == $name)] | if length == 1 then .[0].id else empty end')"

  if [[ -z "${user_id}" ]]; then
    fail "No single user matches ZITADEL_BOOTSTRAP_ADMIN_USERNAME=${ZITADEL_BOOTSTRAP_ADMIN_USERNAME}"
  fi

  existing="$(api POST /management/v1/users/grants/_search '{}' |
    jq -r --arg project "${PROJECT_ID}" --arg user "${user_id}" \
      '.result[]? | select(.projectId == $project and .userId == $user) | .id // empty')"

  if [[ -n "${existing}" ]]; then
    info "already granted (${existing})"
    return
  fi

  api POST "/management/v1/users/${user_id}/grants" \
    "$(jq -nc --arg project "${PROJECT_ID}" --arg roles "${ZITADEL_BOOTSTRAP_ADMIN_ROLES:-platform_admin}" \
      '{projectId: $project, roleKeys: ($roles | split(","))}')" >/dev/null
  done_ "granted ${ZITADEL_BOOTSTRAP_ADMIN_ROLES:-platform_admin} to ${user_id}"
}

# service-player has to grant the player role itself when someone registers:
# Zitadel refuses a token to a user with no role, and nothing inside Zitadel can
# add one on v4 (Actions v1 had appendUserGrant and no longer fires). So it
# needs an account of its own — ORG_OWNER scoped to this org, not IAM_OWNER.
ensure_provisioner_account() {
  step "Provisioner account: ${PROVISIONER_USERNAME}"

  local user_id
  user_id="$(api POST /management/v1/users/_search '{}' |
    jq -r --arg name "${PROVISIONER_USERNAME}" \
      '[.result[]? | select(.userName == $name)] | if length == 1 then .[0].id else empty end')"

  if [[ -n "${user_id}" ]]; then
    info "already exists (${user_id})"
    if provisioner_token_works "${user_id}"; then
      info "its token still works, so a new one is not issued"
      return
    fi
    info "the token in .env does not work — issuing a new one"
  else
    user_id="$(api POST /management/v1/users/machine \
      "$(jq -nc --arg name "${PROVISIONER_USERNAME}" \
        '{userName: $name,
          name: "Player provisioner",
          description: "Grants the player role to self-registered users",
          accessTokenType: "ACCESS_TOKEN_TYPE_BEARER"}')" | jq -r '.userId')"

    api POST /management/v1/orgs/me/members \
      "$(jq -nc --arg user "${user_id}" '{userId: $user, roles: ["ORG_OWNER"]}')" >/dev/null

    done_ "created ${PROVISIONER_USERNAME} (${user_id})"
  fi

  PROVISIONER_TOKEN="$(api POST "/management/v1/users/${user_id}/pats" \
    "$(jq -nc --arg expiry "${ZITADEL_PROVISIONER_PAT_EXPIRATION}" '{expirationDate: $expiry}')" |
    jq -r '.token')"

  done_ "issued a token for ${PROVISIONER_USERNAME}"
}

# A PAT is shown once, at creation, so .env is the only copy of it. The account
# outliving a usable token is an ordinary state: a rebuilt .env, an expired
# token, a run that died between creating the account and writing the token
# back. Finding the account is therefore not evidence that provisioning works,
# and the failure is silent — registration succeeds and the user gets no role.
# So ask Zitadel. The id has to match too, or a stale token belonging to some
# other account would pass.
provisioner_token_works() {
  local expected_user_id="$1"
  [[ -n "${ZITADEL_PROVISIONER_TOKEN:-}" ]] || return 1

  local response status
  response="$(curl -sS -w $'\n%{http_code}' "${ZITADEL_ISSUER_URI%/}/auth/v1/users/me" \
    -H "Authorization: Bearer ${ZITADEL_PROVISIONER_TOKEN}")" || return 1

  status="${response##*$'\n'}"
  [[ "${status}" == 2* ]] || return 1

  [[ "$(jq -r '.user.id // empty' <<<"${response%$'\n'*}")" == "${expected_user_id}" ]]
}

write_back() {
  step "Writing generated values back"

  set_env_value ZITADEL_PROJECT_ID "${PROJECT_ID}"
  set_env_value ZITADEL_PORTAL_CLIENT_ID "${PORTAL_CLIENT_ID}"
  printf '%s\n' "${PORTAL_CLIENT_ID}" >"${CLIENT_ID_FILE}"
  info "client id → .env, .client-id"

  if [[ -n "${SIGNING_KEY:-}" ]]; then
    set_env_value ZITADEL_WEBHOOK_SIGNING_KEY "${SIGNING_KEY}"
    info "signing key → .env"
  fi

  if [[ -n "${PROVISIONER_TOKEN:-}" ]]; then
    set_env_value ZITADEL_PROVISIONER_TOKEN "${PROVISIONER_TOKEN}"
    info "provisioner token → .env"
  fi

  # The portal reads this at startup, so a rebuilt instance changes no tracked
  # file. It is gitignored for that reason: the client id belongs to one
  # instance, and a commit carrying it would mean nothing.
  #
  # jq writes beside the target, never over it: a redirect truncates the file
  # before jq runs, so a failure there would leave the portal with an empty
  # config and no way to start. mv is atomic and the file holds nothing secret,
  # so unlike .env it can be replaced rather than written through. mktemp makes
  # it 0600; whatever serves it later has to be able to read it.
  local config_dir tmp
  config_dir="$(dirname "${PORTAL_CONFIG}")"
  mkdir -p "${config_dir}"
  tmp="$(mktemp "${config_dir}/.config.json.XXXXXX")" || fail "cannot write in ${config_dir}"

  if jq -n \
    --arg issuer "${ZITADEL_ISSUER_URI}" \
    --arg clientId "${PORTAL_CLIENT_ID}" \
    --arg apiBaseUrl "${PORTAL_API_BASE_URL}" \
    '{zitadelIssuerUri: $issuer, zitadelClientId: $clientId, apiBaseUrl: $apiBaseUrl}' \
    >"${tmp}" && chmod 644 "${tmp}" && mv "${tmp}" "${PORTAL_CONFIG}"; then
    info "portal config → frontend-portal/public/config.json"
  else
    rm -f "${tmp}"
    fail "could not write ${PORTAL_CONFIG}"
  fi
}

main() {
  require_tools
  load_env
  require_env ZITADEL_ISSUER_URI ZITADEL_PROJECT_NAME ZITADEL_OIDC_APP_NAME \
    ZITADEL_OIDC_REDIRECT_URI ZITADEL_OIDC_POST_LOGOUT_URI \
    ZITADEL_OIDC_ALLOWED_ORIGIN ZITADEL_TARGET_ENDPOINT PORTAL_API_BASE_URL

  TARGET_NAME="player-provisioning"
  PROVISIONER_USERNAME="player-provisioner"
  : "${ZITADEL_PROVISIONER_PAT_EXPIRATION:=${ZITADEL_ADMIN_PAT_EXPIRATION}}"
  # user.human.added, not selfregistered. LoginV2 registers users by calling the
  # v2 API as the login client, so a self-registration raises "added" like any
  # other creation — verified against a real registration. The selfregistered
  # event is a login-v1 leftover that never fires here, and binding it meant the
  # target never ran at all.
  PROVISIONING_EVENT="user.human.added"

  read_admin_pat
  identify_caller

  find_or_create_project
  ensure_roles
  find_or_create_oidc_app
  ensure_target
  ensure_execution
  grant_bootstrap_admin
  ensure_provisioner_account
  write_back
  revoke_admin_pat

  echo
  done_ "Zitadel is configured. Restart service-player so it picks up the signing key."
}

main "$@"
